'use client';

import { Suspense, useEffect, useState, useRef } from 'react';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { AlertCircle, ChevronLeft, Download, Loader2, ShoppingBag } from 'lucide-react';
import { publicApi } from '@/lib/api';
import { TicketVisual } from '@/components/billetterie/TicketCard';

type TicketRow = {
  ticketId: string;
  serialNumber: string;
  templateName: string;
  price: number;
  currency: string;
};

type Status = 'checking' | 'completed' | 'failed';

type MerchOrder = {
  code: string;
  fulfillment: 'PICKUP' | 'DELIVERY';
  items: { productName: string; size: string | null; color: string | null; quantity: number }[];
};

type EventInfo = { name: string; startDate: string; venue: string; city: string };

/** PDF of one ticket, generated by the server (same file as the one sent by e-mail) */
function openPdf(reference: string, ticketId: string) {
  window.open(`/api/public/payments/${reference}/tickets/${ticketId}/pdf`, '_blank', 'noopener,noreferrer');
}

function SuccessContent() {
  const params = useSearchParams();
  const reference = params.get('reference');
  const [status, setStatus] = useState<Status>('checking');
  const [tickets, setTickets] = useState<TicketRow[]>([]);
  const [merchOrder, setMerchOrder] = useState<MerchOrder | null>(null);
  const [event, setEvent] = useState<EventInfo | null>(null);
  const [holder, setHolder] = useState<{ name: string; email: string }>({ name: '', email: '' });
  const intervalRef = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    if (!reference) { setStatus('failed'); return; }

    const poll = async () => {
      try {
        const res = await publicApi.getPaymentStatus(reference);
        const d = (res.data as any).data ?? res.data;
        if (d.status === 'COMPLETED') {
          if (intervalRef.current) clearInterval(intervalRef.current);
          setTickets(d.tickets ?? []);
          setMerchOrder(d.merchOrder ?? null);
          setEvent(d.event ?? null);
          setHolder({ name: d.holderName ?? '', email: d.holderEmail ?? '' });
          setStatus('completed');
        } else if (d.status === 'FAILED' || d.status === 'CANCELLED') {
          if (intervalRef.current) clearInterval(intervalRef.current);
          setStatus('failed');
        }
      } catch {
        // keep polling
      }
    };

    poll();
    intervalRef.current = setInterval(poll, 4000);
    return () => { if (intervalRef.current) clearInterval(intervalRef.current); };
  }, [reference]);

  return (
    <div className="min-h-screen bg-white px-6 pb-16 pt-6 text-black">
      <div className="mx-auto max-w-[420px]">
        <Link href="/billetterie" aria-label="Retour à la billetterie" className="inline-flex h-11 w-11 items-center justify-center rounded-full bg-black text-white">
          <ChevronLeft className="h-6 w-6" strokeWidth={2.5} />
        </Link>

        {status === 'checking' && (
          <div className="py-24 text-center">
            <Loader2 className="mx-auto h-10 w-10 animate-spin text-black" />
            <h1 className="mt-6 text-2xl font-black uppercase tracking-tight">Confirmation du paiement</h1>
            <p className="mt-2 text-[#555]">Patientez quelques secondes pendant la validation de votre paiement.</p>
          </div>
        )}

        {status === 'completed' && (
          <>
            <div className="mt-8">
              <h1 className="text-3xl font-black uppercase leading-none tracking-tight">
                {tickets.length > 1 ? 'Vos billets' : tickets.length === 1 ? 'Votre billet' : 'Commande confirmée'}
              </h1>
              {event && <p className="mt-2 text-lg font-semibold">{event.name}</p>}
              <p className="mt-2 text-[15px] text-[#555]">
                Paiement confirmé. {tickets.length > 0 ? 'Vos billets vous ont aussi été envoyés' : 'Le récapitulatif vous a été envoyé'} par e-mail
                {holder.email ? <> à <strong className="text-black">{holder.email}</strong></> : ''}.
              </p>
            </div>

            <div className="mt-8 space-y-6">
              {tickets.map((t, i) => (
                <div key={t.ticketId} className="flex flex-col items-center">
                  <TicketVisual data={{
                    ticketId: t.ticketId,
                    serialNumber: t.serialNumber,
                    holderName: holder.name,
                    eventName: event?.name ?? '',
                    templateName: t.templateName,
                    price: t.price,
                    currency: t.currency,
                    eventStart: event?.startDate,
                    eventVenue: event?.venue,
                    eventCity: event?.city,
                    ticketIndex: i + 1,
                    totalTickets: tickets.length,
                  }} />
                  <button
                    type="button"
                    onClick={() => openPdf(reference!, t.ticketId)}
                    className="mt-3 inline-flex items-center gap-2 rounded-full border border-black px-5 py-2 text-sm font-semibold transition-colors hover:bg-black hover:text-white"
                  >
                    <Download className="h-4 w-4" /> Télécharger le PDF
                  </button>
                </div>
              ))}
            </div>

            {merchOrder && (
              <div className="mt-8 rounded-[24px] border border-[#c9c9c9] p-5">
                <p className="flex items-center gap-2 font-semibold">
                  <ShoppingBag className="h-4 w-4" /> Commande boutique <span className="font-mono">{merchOrder.code}</span>
                </p>
                <ul className="mt-2 space-y-0.5 text-sm">
                  {merchOrder.items.map((it, idx) => (
                    <li key={idx}>
                      {it.quantity} × {it.productName}
                      {(it.size || it.color) && ` (${[it.size, it.color].filter(Boolean).join(' · ')})`}
                    </li>
                  ))}
                </ul>
                <p className="mt-2 text-xs text-[#555]">
                  {merchOrder.fulfillment === 'PICKUP'
                    ? `À retirer sur place : présentez le QR code reçu par e-mail ou le code ${merchOrder.code}.`
                    : 'Livraison : vous serez prévenu(e) par e-mail de l’expédition.'}
                </p>
              </div>
            )}

            <p className="mt-8 text-center text-sm text-[#555]">Présentez le QR code à l’entrée, sur votre téléphone ou imprimé.</p>
          </>
        )}

        {status === 'failed' && (
          <div className="py-24 text-center">
            <AlertCircle className="mx-auto h-12 w-12 text-red-600" strokeWidth={1.5} />
            <h1 className="mt-6 text-2xl font-black uppercase tracking-tight">Paiement non confirmé</h1>
            <p className="mt-2 text-[#555]">Le paiement n’a pas pu être confirmé. Aucun montant n’a été débité.</p>
            <Link href="/billetterie" className="mt-8 inline-block rounded-full bg-black px-6 py-3 font-semibold uppercase text-white">
              Retour à la billetterie
            </Link>
          </div>
        )}
      </div>
    </div>
  );
}

export default function PaymentSuccessPage() {
  return (
    <Suspense fallback={
      <div className="flex min-h-screen items-center justify-center bg-white">
        <Loader2 className="h-8 w-8 animate-spin text-black" />
      </div>
    }>
      <SuccessContent />
    </Suspense>
  );
}
